### ISSUE TITLE
Dnfdragora 2.1.0 window height

### ISSUE THREAD

**Issue by L-U-T-i** [manatools/dnfdragora#164]
Since version 2.1.0, dnfdragora opens a window with vertical size of about 840 ÷ 850 px (estimated) / approx. 14.5 lines in package list + apprpox. 11 lines in the bottom pane. It is not possible to resize / decrease the height of this window. Increase is possible. It is a VNC session (virtual server CentOS 8.2 with a custom build of dnfdragora / dnfdaemon / libyui & co. - based on Fedora packages...). I can't test with a monitor at the moment, unfortunately, but I guess it should be just the same.

Not that it would sometimes be convenient / desired to reduce the window height, it makes dnfdragora useless if screen resolution is 800 px vertical or less, as buttons at the bottom are not visible / accessible.

With exactly the same "environment" (libyui & co.), the min.height of previous version (2.0.4) window was not that big, so it has to be something introduced by some of the recent commits.

Screenshots:
![Screenshot-1](https://user-images.githubusercontent.com/50832205/93399777-863e0280-f87e-11ea-93cb-c7e33181f305.png)

![Screenshot-2](https://user-images.githubusercontent.com/50832205/93399796-8f2ed400-f87e-11ea-8149-b05c097833c0.png)

_Originally posted by @L-U-T-i in https://github.com/manatools/dnfdragora/issues/163#issuecomment-693703988_

**Comment by MattEttus** [comment]
It doesn't even matter what the screen height is, dnfdragora always makes the window bigger than the screen.  My screen is 2560x1440 and the window is bigger than the screen.  Even if I use alt-click to move the window up so I can see the bottom of the window, it moves itself back.

**Comment by anaselli** [comment]
Thanks for reporting additional information, as said it is a libyui-gtk issue, but the the minimum size that i don't know why is came out since i didn't change the code in such a direction. 
libyui-gtk is a low priority task i work on, since it should be a Suse job... help is welcome of course.
In the mean while you could try dnfdragora-qt if that works better...

**Comment by L-U-T-i** [comment]
In dnfdragora-qt (run by "dnfdragora --qt"), the window size can be reduced as needed. The only issue is everything is reduced proportionally (issue with dialog entries, which eventually become too low and the texts are not readable anymore... as in my screenshot attached - items above the update list window).

What I find interesting is that the main window height in dnfdragora-gtk can not be reduced below cetrain size, while the height of a dialog window (as "System options" on my screenshot) can (see the button heights at the bottom, which started to shrink already - and, it can be reduced futrher on...).

Here is a dnfrdagora-gtk ("dnfdragora --gtk") screenshot:
![dnfdragora-gtk](https://user-images.githubusercontent.com/50832205/96572269-ec2e0780-12cc-11eb-8806-54342d225916.png)

and here is a dnfdragora-qt ("dnfdragora --qt") screenshot:
![dnfdragora-qt](https://user-images.githubusercontent.com/50832205/96572308-f819c980-12cc-11eb-9abc-28897c7bc033.png)

**Comment by L-U-T-i** [comment]
Don't know it it has anything to do with this issue, but I see really a lot of the following outputs when dnfdragora-gtk is launched in shell:

> /usr/lib64/python3.6/site-packages/yui.py:1938: Warning: Source ID <xxxx> was not found when attempting to remove it
  return _yui.YDialog_waitForEvent(self, timeout_millisec)

<xxxx> is a value starting from 42 and increasing - 42, 73, 89, 103, 110, 112, 144, 116118, 120, 122 etc (increased mainly by 2, sometimes by more...)

There is no such output in dnfdragora-qt.

**Comment by anaselli** [comment]
Iirc, that warning should be fixed in libyui-gtk, a newer version than the one used in fedora 32. But other ones could be survived....
Dnfdragora options use minimum size if iirc, will see to try adding to main dialog too as a test...

**Comment by anaselli** [comment]
I experienced the same issue using isodumper --gtk and manafirewall --gtk

**Comment by anaselli** [comment]
i seem i can't reduce the size too much in height, i tried without luck to understand where the problem is. Combobox and list box iirc cannot be reduced (gtk only) and maybe some other widgets too so i suspect a sum of min size required there...
Anyway the patch https://github.com/anaselli/libyui-gtk/commit/ec683943d02a2c1fcd2d5b425a5ad0fbbbf34fd2 seems to fix the full screen size start up.

**Comment by pgrahamdev** [comment]
This problem still exists in dnfdragora 2.1.2 on Fedora 36 (dnfdragora-2.1.2-1.fc36.noarch) running under the Fedora 36 Xfce spin.  Not being able to see the bottom of the window is confusing and frustrating, of course, since you might not understand that the "Apply" and "Select All" buttons even exist.  The machine I am using has a 1366x768 screen resolution and has libyui-gtk 2.52.0 (libyui-gtk-2.52.0-2.fc36.x86_64), if that is relevant.  As noted above, I cannot shrink the size of the window vertically at all to get to those buttons.  In Xfce, if I use Alt-LeftClick on the dnfdragora window and then drag the window up so I can use the buttons. Any suggestions on where to look to fix this issue or what information someone my need to understand the problem better?

**Comment by andycuccaro** [comment]
> This problem still exists in dnfdragora 2.1.2 on Fedora 36 (dnfdragora-2.1.2-1.fc36.noarch) running under the Fedora 36 Xfce spin. Not being able to see the bottom of the window is confusing and frustrating, of course, since you might not understand that the "Apply" and "Select All" buttons even exist. The machine I am using has a 1366x768 screen resolution and has libyui-gtk 2.52.0 (libyui-gtk-2.52.0-2.fc36.x86_64), if that is relevant. As noted above, I cannot shrink the size of the window vertically at all to get to those buttons. In Xfce, if I use Alt-LeftClick on the dnfdragora window and then drag the window up so I can use the buttons. Any suggestions on where to look to fix this issue or what information someone my need to understand the problem better?

What I managed to do was to momentarily change the display scale to 1.5x in order to fully display the whole window. I hope that helps. And lets hope this can be officially solved soon.

**Comment by anaselli** [comment]
Hmm this line seem suspicious to me
https://github.com/libyui/libyui-gtk/blob/master/src/YGUI.cc#L702
